//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenneEngin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenneEngin()
        {
            this.Vehicules = new HashSet<Vehicule>();
        }
    
        public int Id { get; set; }
        public string Matricule { get; set; }
        public string Marque { get; set; }
        public Nullable<int> AnneeAchat { get; set; }
        public Nullable<decimal> Capacite { get; set; }
        public Nullable<int> IdTypeBenne { get; set; }
        public bool Supprime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicule> Vehicules { get; set; }
        public virtual TypeBenneEngin TypeBenneEngin { get; set; }
    }
}
