//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depense
    {
        public int Id { get; set; }
        public decimal Montant { get; set; }
        public int IdTypeDepense { get; set; }
        public Nullable<int> IdVoyage { get; set; }
        public Nullable<int> IdHistoriquePanne { get; set; }
        public bool Supprime { get; set; }
    
        public virtual HistoriquePanne HistoriquePanne { get; set; }
        public virtual Voyage Voyage { get; set; }
        public virtual TypeDepense TypeDepense { get; set; }
    }
}
