//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsDroitAcce
    {
        public int Id { get; set; }
        public int IdMenu { get; set; }
        public int IdDroidAcces { get; set; }
        public bool Supprime { get; set; }
    
        public virtual DroitAcce DroitAcce { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
