//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public long Id { get; set; }
        public byte[] datejournal { get; set; }
        public string evenement { get; set; }
        public Nullable<int> idutilisateur { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
