//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mTransport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AffectationVehicule> AffectationVehicules { get; set; }
        public virtual DbSet<BenneEngin> BenneEngins { get; set; }
        public virtual DbSet<Chauffeur> Chauffeurs { get; set; }
        public virtual DbSet<Depense> Depenses { get; set; }
        public virtual DbSet<DetailsDroitAcce> DetailsDroitAcces { get; set; }
        public virtual DbSet<DroitAcce> DroitAcces { get; set; }
        public virtual DbSet<Formulaire> Formulaires { get; set; }
        public virtual DbSet<HistoriquePanne> HistoriquePannes { get; set; }
        public virtual DbSet<journal> journals { get; set; }
        public virtual DbSet<Materiel> Materiels { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Profil> Profils { get; set; }
        public virtual DbSet<RaisonSociale> RaisonSociales { get; set; }
        public virtual DbSet<TeteEngin> TeteEngins { get; set; }
        public virtual DbSet<TypeBenneEngin> TypeBenneEngins { get; set; }
        public virtual DbSet<TypeDepense> TypeDepenses { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
        public virtual DbSet<Voyage> Voyages { get; set; }
    }
}
