//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaisonSociale
    {
        public int Id { get; set; }
        public string NomSociete { get; set; }
        public string Adresse { get; set; }
        public string BoitePostale { get; set; }
        public string Quartier { get; set; }
        public string Ville { get; set; }
        public string Pays { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Siteweb { get; set; }
        public string NomDirecteur { get; set; }
        public string PrenomDirecteur { get; set; }
        public string SignatureDirecteur { get; set; }
        public string Logo { get; set; }
    }
}
