//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.journals = new HashSet<journal>();
        }
    
        public int Id { get; set; }
        public string Pseudo { get; set; }
        public string NomUtilisateur { get; set; }
        public string PrenomUtilisateur { get; set; }
        public string Telephone { get; set; }
        public string BP { get; set; }
        public string Email { get; set; }
        public string MotDePasse { get; set; }
        public bool EstSuperutilisateur { get; set; }
        public bool Estactif { get; set; }
        public Nullable<int> IdProfil { get; set; }
        public string photo { get; set; }
        public bool Supprime { get; set; }
        public Nullable<System.DateTime> DateExpirationPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<journal> journals { get; set; }
        public virtual Profil Profil { get; set; }
    }
}
